version: "3"

tasks:
  css:
    desc: Compile les feuilles de styles CSS
    watch: true
    cmds:
      - pnpm exec lessc --rewrite-urls=local assets/less/goat.theme.less assets/css/main.css
    sources:
      - assets/less/*.less
    generates:
      - assets/css/main.css

  preview:
    desc: Affiche une pré-version du site localement
    interactive: true
    deps: [css]
    cmds:
      - hugo server --buildDrafts

  clean:
    desc: Fait du nettoyage
    cmds:
      - rm -r ./public/
